server {
    listen 80;
    server_name zhangff.cn www.zhangff.cn;
    # 前端：如果你的前端是独立服务，这里配置 / 转发；如果是前后端一体，可删除
    location / {
        proxy_pass http://agent_app:3000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}